"""
Generate K-line charts for symbols that have MA Convergence signals in a scan CSV,
and enrich a summary table with extra stock info (name, market cap, daily pct change).

Inputs:
1) scan CSV generated by scanners/scan_ma_convergence_daily.py
2) local daily cache: data_cache/{symbol}_{years}y_1d_forward.csv

Outputs:
- PNG charts (candles + volume + MA + buy/sell markers)
- charts.csv (enriched)
- index.html (preview)

Example:
    python scripts/generate_ma_convergence_charts_from_scan.py ^
      --scan-csv results/ma_convergence_daily_scan_mv100yi_20260302_144411/ma_convergence_scan_20260302_145754.csv ^
      --data-years 20 --plot-years 5 --workers 4
"""

from __future__ import annotations

import argparse
import concurrent.futures as cf
import contextlib
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import mplfinance as mpf
import numpy as np
import pandas as pd
from pandas.tseries.offsets import BDay

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from indicators.ma_convergence_strategy import calculate_indicators, generate_signals  # noqa: E402


def _try_import_akshare():
    try:
        import akshare as ak  # type: ignore

        return ak
    except Exception:
        return None


_A_SHARE_SYMBOL_RE = re.compile(r"^\d{6}\.(SZ|SS|BJ)$", re.IGNORECASE)


@dataclass(frozen=True)
class Job:
    symbol: str
    data_path: Path


def _load_daily(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path, index_col="datetime", parse_dates=True)
    if not isinstance(df.index, pd.DatetimeIndex):
        df.index = pd.to_datetime(df.index, errors="coerce")
    df = df.sort_index()
    cols = [c for c in ["Open", "High", "Low", "Close", "Volume"] if c in df.columns]
    return df[cols].copy()


def _last_years(df: pd.DataFrame, years: int) -> pd.DataFrame:
    if df is None or df.empty:
        return pd.DataFrame()
    end_ts = df.index.max()
    start_ts = end_ts - pd.DateOffset(years=int(years))
    return df.loc[df.index >= start_ts].copy()


def _markers(df_view: pd.DataFrame, signals_view: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    buy_mask = (signals_view.get("signal", 0) == 1).reindex(df_view.index, fill_value=False)
    sell_mask = (signals_view.get("signal", 0) == -1).reindex(df_view.index, fill_value=False)

    buy_y = pd.Series(index=df_view.index, data=np.nan, dtype="float64")
    sell_y = pd.Series(index=df_view.index, data=np.nan, dtype="float64")

    if buy_mask.any():
        buy_y.loc[buy_mask] = (df_view.loc[buy_mask, "Low"] * 0.99).astype(float)
    if sell_mask.any():
        sell_y.loc[sell_mask] = (df_view.loc[sell_mask, "High"] * 1.01).astype(float)

    return buy_y, sell_y


def _pad_plot_right(df_view: pd.DataFrame, bars: int = 2) -> pd.DataFrame:
    """Append empty bars on the right side to avoid clipping the last candle."""
    if df_view is None or df_view.empty:
        return df_view

    n = max(0, int(bars))
    if n == 0:
        return df_view

    if not isinstance(df_view.index, pd.DatetimeIndex):
        return df_view

    out = df_view.copy()
    idx = out.index
    last = idx.max()

    # Try to keep original spacing; fallback to business-day bars.
    inferred_offset = None
    if len(idx) >= 3:
        try:
            freq = pd.infer_freq(idx[-min(len(idx), 20) :])
            if freq:
                inferred_offset = pd.tseries.frequencies.to_offset(freq)
        except Exception:
            inferred_offset = None

    step = inferred_offset if inferred_offset is not None else BDay(1)
    future_idx = []
    current = last
    for _ in range(n):
        try:
            current = current + step
        except Exception:
            current = current + pd.Timedelta(days=1)
        future_idx.append(current)

    pad = pd.DataFrame(index=pd.DatetimeIndex(future_idx), columns=out.columns, dtype="float64")
    out = pd.concat([out, pad], axis=0)
    return out


def _plot_symbol(
    symbol: str,
    df_view: pd.DataFrame,
    signals_view: pd.DataFrame,
    out_png: Path,
    title: str,
    style: str,
    mav: tuple[int, ...],
    dpi: int,
):
    df_plot = _pad_plot_right(df_view, bars=2)
    signals_plot = signals_view.reindex(df_plot.index)

    addplots = []
    buy_y, sell_y = _markers(df_plot, signals_plot)
    if buy_y.notna().any():
        addplots.append(mpf.make_addplot(buy_y, type="scatter", markersize=60, marker="^", color="g", panel=0))
    if sell_y.notna().any():
        addplots.append(mpf.make_addplot(sell_y, type="scatter", markersize=60, marker="v", color="r", panel=0))

    plot_kwargs = dict(
        type="candle",
        style=style,
        volume=True,
        mav=mav,
        title=title,
        ylabel="Price",
        ylabel_lower="Volume",
        warn_too_much_data=len(df_plot) + 500,
        figsize=(16, 10),
        tight_layout=True,
        savefig=dict(fname=str(out_png), dpi=dpi, bbox_inches="tight", pad_inches=0.2),
    )
    if addplots:
        plot_kwargs["addplot"] = addplots

    mpf.plot(df_plot, **plot_kwargs)


@contextlib.contextmanager
def _temporary_proxy_env(proxy: str | None, inherit: bool):
    """
    Temporarily control proxy-related environment variables for network calls.

    - inherit=True: keep current environment unchanged
    - inherit=False: clear existing proxy vars; if proxy is provided, set it for HTTP/HTTPS.
    """

    if inherit:
        yield
        return

    keys = [
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "http_proxy",
        "https_proxy",
        "ALL_PROXY",
        "all_proxy",
        "NO_PROXY",
        "no_proxy",
    ]
    old: dict[str, str] = {}
    for k in keys:
        if k in os.environ:
            old[k] = os.environ.pop(k)

    if proxy:
        os.environ["HTTP_PROXY"] = proxy
        os.environ["HTTPS_PROXY"] = proxy
        os.environ["http_proxy"] = proxy
        os.environ["https_proxy"] = proxy

    try:
        yield
    finally:
        for k in keys:
            os.environ.pop(k, None)
        os.environ.update(old)


def _fetch_spot_map(*, proxy: str | None, inherit_proxy_env: bool) -> dict[str, dict]:
    """
    Fetch A-share spot snapshot and return code->info mapping.
    Uses AkShare if available; otherwise returns empty map.
    """
    ak = _try_import_akshare()
    if ak is None:
        return {}

    def _try_fetch(*, _proxy: str | None, _inherit: bool):
        try:
            with _temporary_proxy_env(_proxy, inherit=_inherit):
                return ak.stock_zh_a_spot_em()
        except Exception:
            return None

    spot = None
    if proxy:
        spot = _try_fetch(_proxy=str(proxy), _inherit=False)
    else:
        spot = _try_fetch(_proxy=None, _inherit=inherit_proxy_env)
        if spot is None and not inherit_proxy_env:
            # Retry inheriting env proxy settings if direct fetch failed.
            spot = _try_fetch(_proxy=None, _inherit=True)

    if spot is None:
        return {}

    if spot is None or spot.empty:
        return {}

    # Normalize columns (Eastmoney)
    col_code = "代码" if "代码" in spot.columns else None
    col_name = "名称" if "名称" in spot.columns else None
    col_price = "最新价" if "最新价" in spot.columns else None
    col_pct = "涨跌幅" if "涨跌幅" in spot.columns else None
    col_mv = "总市值" if "总市值" in spot.columns else None

    if not col_code:
        return {}

    out: dict[str, dict] = {}
    for _, r in spot.iterrows():
        code = str(r[col_code]).strip()
        if not re.match(r"^\d{6}$", code):
            continue
        out[code] = {
            "name": str(r[col_name]).strip() if col_name else "",
            "price": float(r[col_price]) if col_price and pd.notna(r[col_price]) else np.nan,
            "pct_chg": float(r[col_pct]) if col_pct and pd.notna(r[col_pct]) else np.nan,
            "total_mv": float(r[col_mv]) if col_mv and pd.notna(r[col_mv]) else np.nan,  # RMB
        }
    return out


def _load_meta_map(meta_csv: Path) -> dict[str, dict]:
    """
    Load local meta CSV (e.g. results/a_share_total_mv_ge_100yi_*.csv) and return code->info mapping.

    Expected columns (best-effort): code, name, trade, total_mv_yi.
    """

    if meta_csv is None or not meta_csv.exists():
        return {}

    try:
        df = pd.read_csv(meta_csv, dtype={"code": str})
    except Exception:
        return {}

    if df is None or df.empty:
        return {}

    col_code = "code" if "code" in df.columns else ("代码" if "代码" in df.columns else None)
    col_name = "name" if "name" in df.columns else ("名称" if "名称" in df.columns else None)
    col_trade = "trade" if "trade" in df.columns else ("最新价" if "最新价" in df.columns else None)
    col_mv_yi = "total_mv_yi" if "total_mv_yi" in df.columns else None
    col_asof = "asof" if "asof" in df.columns else None

    if not col_code:
        return {}

    out: dict[str, dict] = {}
    for _, r in df.iterrows():
        code = str(r.get(col_code, "")).strip()
        if not re.match(r"^\d{6}$", code):
            continue
        name = str(r.get(col_name, "")).strip() if col_name else ""
        price = r.get(col_trade, np.nan) if col_trade else np.nan
        try:
            price = float(price) if pd.notna(price) else np.nan
        except Exception:
            price = np.nan

        mv_yi = r.get(col_mv_yi, np.nan) if col_mv_yi else np.nan
        try:
            mv_yi = float(mv_yi) if pd.notna(mv_yi) else np.nan
        except Exception:
            mv_yi = np.nan

        total_mv = (mv_yi * 1e8) if pd.notna(mv_yi) else np.nan
        meta_asof = str(r.get(col_asof, "")).strip() if col_asof else ""

        out[code] = {
            "name": name,
            "price": price,
            "pct_chg": np.nan,
            "total_mv": total_mv,  # RMB
            "total_mv_yi": mv_yi,  # 1e8 RMB
            "meta_asof": meta_asof,
        }

    return out


def _scan_hit_symbols(scan_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(scan_csv, dtype={"symbol": str})
    if df.empty or "symbol" not in df.columns:
        return pd.DataFrame()
    df["symbol"] = df["symbol"].astype(str).str.strip()
    df = df[df["symbol"].str.len() > 0].copy()
    df = df[df["symbol"].str.match(_A_SHARE_SYMBOL_RE, na=False)].copy()
    return df


def _resolve_scan_csv(scan_csv_arg: str, scan_dir_arg: str) -> Path:
    """
    Resolve scan CSV path.

    Priority:
    1) --scan-csv if provided
    2) latest CSV under --scan-dir (default: results/ma_convergence_daily_scan)
    """
    if str(scan_csv_arg).strip():
        p = Path(scan_csv_arg)
        if not p.exists():
            raise SystemExit(f"--scan-csv not found: {scan_csv_arg}")
        return p

    scan_dir = Path(scan_dir_arg)
    if not scan_dir.exists():
        raise SystemExit(f"--scan-dir not found: {scan_dir_arg}")

    candidates = sorted(scan_dir.glob("ma_convergence_scan_*.csv"), key=lambda x: x.stat().st_mtime, reverse=True)
    if not candidates:
        candidates = sorted(scan_dir.glob("*.csv"), key=lambda x: x.stat().st_mtime, reverse=True)
    if not candidates:
        raise SystemExit(f"No scan CSV found under --scan-dir: {scan_dir_arg}")
    return candidates[0]


def _build_jobs(scan_df: pd.DataFrame, data_dir: Path, data_years: int) -> list[Job]:
    suffix = f"_{int(data_years)}y_1d_forward.csv"
    symbols = sorted(set(scan_df["symbol"].astype(str).tolist()))
    jobs: list[Job] = []
    missing = 0
    for sym in symbols:
        p = data_dir / f"{sym}{suffix}"
        if p.exists():
            jobs.append(Job(symbol=sym, data_path=p))
        else:
            missing += 1
    if missing:
        print(f"[WARN] missing daily cache for {missing}/{len(symbols)} symbols (years={data_years})")
    return jobs


def _worker(args):
    job, plot_years, style, mav, dpi, signal_params, out_dir, spot_map, scan_df = args
    try:
        df = _load_daily(job.data_path)
        if df.empty or len(df) < 140:
            return None

        df_ind = calculate_indicators(df, volume_ma_period=int(signal_params.get("volume_ma_period", 20)))
        sig = generate_signals(df_ind, **signal_params)

        df_view = _last_years(df, int(plot_years))
        if df_view.empty or len(df_view) < 60:
            return None
        sig_view = sig.reindex(df_view.index)

        # Latest close and date
        last_dt = df_view.index.max()
        last_close = float(df_view["Close"].iloc[-1])

        # Scan-window hits
        scan_sub = scan_df[scan_df["symbol"] == job.symbol]
        last_scan_date = str(scan_sub["date"].iloc[0]) if ("date" in scan_sub.columns and len(scan_sub) > 0) else ""
        buy_hits = int((scan_sub.get("signal") == "BUY").sum()) if "signal" in scan_sub.columns else 0
        sell_hits = int((scan_sub.get("signal") == "SELL").sum()) if "signal" in scan_sub.columns else 0

        code = job.symbol.split(".")[0]
        spot = spot_map.get(code, {})
        name = spot.get("name", "")

        total_mv = spot.get("total_mv", np.nan)
        total_mv_yi = spot.get("total_mv_yi", np.nan)
        if pd.notna(total_mv) and not pd.notna(total_mv_yi):
            total_mv_yi = float(total_mv) / 1e8
        if pd.notna(total_mv_yi) and not pd.notna(total_mv):
            total_mv = float(total_mv_yi) * 1e8

        pct_chg = spot.get("pct_chg", np.nan)
        spot_price = spot.get("price", np.nan)
        meta_asof = spot.get("meta_asof", "")

        out_png = Path(out_dir) / f"{job.symbol}.png"

        # Fallback pct change from last two closes if spot is missing/unavailable.
        pct_chg_fallback = np.nan
        if len(df_view) >= 2 and pd.notna(df_view["Close"].iloc[-2]):
            prev_close = float(df_view["Close"].iloc[-2])
            if prev_close != 0:
                pct_chg_fallback = (last_close / prev_close - 1.0) * 100.0
        pct_chg_out = pct_chg if pd.notna(pct_chg) else pct_chg_fallback

        # Keep title ASCII to avoid font/encoding issues on some Windows setups.
        title = (
            f"{job.symbol}  close={last_close:.2f}  "
            f"pct={pct_chg_out if pd.notna(pct_chg_out) else float('nan'):.2f}%  "
            f"mvYi={total_mv_yi if pd.notna(total_mv_yi) else float('nan'):.1f}  "
            f"buyHits={buy_hits} sellHits={sell_hits}"
        )
        _plot_symbol(job.symbol, df_view, sig_view, out_png, title, style, mav, dpi)

        return {
            "symbol": job.symbol,
            "name": name,
            "latest_close": last_close,
            "latest_date": str(pd.Timestamp(last_dt)),
            "spot_price": spot_price,
            "pct_chg": pct_chg_out,
            "total_mv_rmb": total_mv,
            "total_mv_yi": total_mv_yi,
            "meta_asof": meta_asof,
            "scan_last_date": last_scan_date,
            "scan_buy_hits": buy_hits,
            "scan_sell_hits": sell_hits,
            "png": str(out_png),
        }
    except Exception as exc:
        return {"symbol": job.symbol, "error": str(exc), "png": ""}


def _write_index(out_dir: Path, df: pd.DataFrame, title: str) -> Path:
    rows_html = []
    for r in df.to_dict(orient="records"):
        png_name = Path(r.get("png", "")).name
        mv_yi = r.get("total_mv_yi", "")
        try:
            mv_yi = f"{float(mv_yi):.1f}" if mv_yi not in ("", None) and pd.notna(mv_yi) else ""
        except Exception:
            pass

        pct = r.get("pct_chg", "")
        try:
            pct = f"{float(pct):.2f}" if pct not in ("", None) and pd.notna(pct) else ""
        except Exception:
            pass

        latest_date = str(r.get("latest_date", "")).split(" ")[0]
        meta_asof = str(r.get("meta_asof", ""))
        rows_html.append(
            "<tr>"
            f"<td>{r.get('symbol','')}</td>"
            f"<td>{r.get('name','')}</td>"
            f"<td>{mv_yi}</td>"
            f"<td>{pct}</td>"
            f"<td>{r.get('latest_close','')}</td>"
            f"<td>{latest_date}</td>"
            f"<td>{meta_asof}</td>"
            f"<td>{r.get('scan_buy_hits','')}</td>"
            f"<td>{r.get('scan_sell_hits','')}</td>"
            f"<td>{r.get('scan_last_date','')}</td>"
            f"<td><a href=\"{png_name}\">{png_name}</a></td>"
            f"<td><img src=\"{png_name}\" style=\"max-width:520px; height:auto;\"></td>"
            "</tr>"
        )

    html = (
        "<!doctype html><html><head><meta charset=\"utf-8\">"
        f"<title>{title}</title>"
        "<style>body{font-family:Arial,Helvetica,sans-serif} table{border-collapse:collapse;width:100%}"
        "th,td{border:1px solid #ddd;padding:6px;vertical-align:top} th{background:#f5f5f5}"
        "</style></head><body>"
        f"<h2>{title}</h2>"
        "<p>Green ^ = buy, Red v = sell. Volume + moving averages included.</p>"
        "<table><thead><tr>"
        "<th>Symbol</th><th>Name</th><th>MV(1e8 CNY)</th><th>Pct%</th><th>Close</th><th>Date</th><th>MV_AsOf</th>"
        "<th>BuyHits</th><th>SellHits</th><th>LastHit</th><th>PNG</th><th>Preview</th>"
        "</tr></thead><tbody>"
        + "\n".join(rows_html)
        + "</tbody></table></body></html>"
    )
    index_path = out_dir / "index.html"
    index_path.write_text(html, encoding="utf-8")
    return index_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MA Convergence charts for scan hits and enrich table.")
    parser.add_argument("--scan-csv", default="", help="Scan CSV path. If omitted, auto-pick latest under --scan-dir.")
    parser.add_argument("--scan-dir", default="results/ma_convergence_daily_scan", help="Directory used to auto-pick latest scan CSV when --scan-csv is omitted.")
    parser.add_argument("--data-dir", default="data_cache")
    parser.add_argument("--data-years", type=int, default=20)
    parser.add_argument("--plot-years", type=int, default=5)
    parser.add_argument("--out-dir", default="", help="Output directory (default: results/ma_convergence_scan_charts/<scan_name>_<ts>)")
    parser.add_argument("--meta-csv", default="", help="Local meta CSV to enrich name/mv (e.g. results/a_share_total_mv_ge_100yi_*.csv).")
    parser.add_argument("--proxy", default="", help="Proxy for AkShare spot fetch (e.g. http://127.0.0.1:7890). Empty = disable proxy env.")
    parser.add_argument("--inherit-proxy-env", action="store_true", help="Let AkShare inherit current proxy env vars.")
    parser.add_argument("--style", default="charles")
    parser.add_argument("--mav", default="5,10,20,60")
    parser.add_argument("--dpi", type=int, default=160)
    parser.add_argument("--workers", type=int, default=2)
    parser.add_argument("--no-stop-loss", action="store_true")
    parser.add_argument("--time-exit-days", type=int, default=0)
    parser.add_argument(
        "--volume-filter-mode",
        default="none",
        choices=["none", "contraction", "expansion", "contraction_then_expansion"],
    )
    parser.add_argument("--vol-ma", type=int, default=20)
    parser.add_argument("--vol-ratio-max", type=float, default=0.8)
    parser.add_argument("--vol-ratio-min", type=float, default=1.2)
    parser.add_argument("--vol-setup-days", type=int, default=5)
    parser.add_argument("--vol-setup-max", type=float, default=0.8)
    args = parser.parse_args()

    scan_csv = _resolve_scan_csv(args.scan_csv, args.scan_dir)
    print(f"[INFO] using scan_csv={scan_csv}")
    scan_df = _scan_hit_symbols(scan_csv)
    if scan_df.empty:
        print("[WARN] scan CSV empty or invalid")
        return 0

    mav = tuple(int(x.strip()) for x in str(args.mav).split(",") if x.strip())
    if not mav:
        raise SystemExit("--mav must contain at least one integer period")

    base_name = scan_csv.stem
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = Path(args.out_dir) if str(args.out_dir).strip() else Path("results") / "ma_convergence_scan_charts" / f"{base_name}_{ts}"
    out_dir.mkdir(parents=True, exist_ok=True)

    data_dir = Path(args.data_dir)
    jobs = _build_jobs(scan_df, data_dir, int(args.data_years))
    if not jobs:
        print("[WARN] no jobs to plot")
        return 0

    meta_map = {}
    if str(args.meta_csv).strip():
        meta_map = _load_meta_map(Path(args.meta_csv))
        if meta_map:
            print(f"[OK] loaded meta rows={len(meta_map)} from {args.meta_csv}")
        else:
            print(f"[WARN] failed to load meta CSV: {args.meta_csv}")

    spot_map = _fetch_spot_map(proxy=str(args.proxy).strip() or None, inherit_proxy_env=bool(args.inherit_proxy_env))
    if not spot_map:
        print("[WARN] failed to fetch spot info (akshare/network/proxy). Will use meta CSV and price-based pct fallback if available.")

    info_map = dict(meta_map)
    info_map.update(spot_map)

    signal_params = {
        "stop_loss_enabled": (not args.no_stop_loss),
        "time_exit_enabled": int(args.time_exit_days) > 0,
        "max_holding_days": int(args.time_exit_days),
        "volume_filter_enabled": args.volume_filter_mode != "none",
        "volume_filter_mode": args.volume_filter_mode,
        "volume_ma_period": int(args.vol_ma),
        "volume_ratio_max": float(args.vol_ratio_max),
        "volume_ratio_min": float(args.vol_ratio_min),
        "volume_setup_lookback": int(args.vol_setup_days),
        "volume_setup_ratio_max": float(args.vol_setup_max),
    }

    print(f"[INFO] scan_hits={len(set(scan_df['symbol']))} jobs={len(jobs)} out_dir={out_dir}")

    rows = []
    errors = 0
    workers = max(1, int(args.workers))
    tasks = [(j, int(args.plot_years), args.style, mav, int(args.dpi), signal_params, str(out_dir), info_map, scan_df) for j in jobs]
    if workers > 1:
        with cf.ProcessPoolExecutor(max_workers=workers) as ex:
            futs = [ex.submit(_worker, t) for t in tasks]
            for idx, fut in enumerate(cf.as_completed(futs), 1):
                r = fut.result()
                if r is None:
                    continue
                if r.get("error"):
                    errors += 1
                rows.append(r)
                if idx % 10 == 0 or idx == len(futs):
                    print(f"[INFO] progress {idx}/{len(futs)}")
    else:
        for idx, t in enumerate(tasks, 1):
            r = _worker(t)
            if r is None:
                continue
            if r.get("error"):
                errors += 1
            rows.append(r)
            if idx % 10 == 0 or idx == len(tasks):
                print(f"[INFO] progress {idx}/{len(tasks)}")

    df_out = pd.DataFrame(rows)
    if df_out.empty:
        print("[WARN] no outputs generated")
        return 0

    # Keep non-error first
    if "error" in df_out.columns:
        df_ok = df_out[df_out["error"].isna()].copy()
        df_err = df_out[df_out["error"].notna()].copy()
        df_out = pd.concat([df_ok, df_err], ignore_index=True)

    # Ensure columns exist for sorting/display
    for col, default in [
        ("scan_buy_hits", 0),
        ("scan_sell_hits", 0),
        ("total_mv_yi", np.nan),
        ("pct_chg", np.nan),
        ("latest_close", np.nan),
        ("name", ""),
        ("png", ""),
    ]:
        if col not in df_out.columns:
            df_out[col] = default

    df_out["scan_buy_hits"] = pd.to_numeric(df_out["scan_buy_hits"], errors="coerce").fillna(0).astype(int)
    df_out["scan_sell_hits"] = pd.to_numeric(df_out["scan_sell_hits"], errors="coerce").fillna(0).astype(int)
    df_out["total_mv_yi"] = pd.to_numeric(df_out["total_mv_yi"], errors="coerce")

    df_out = df_out.sort_values(["scan_buy_hits", "total_mv_yi", "symbol"], ascending=[False, False, True])

    out_csv = out_dir / "charts.csv"
    df_out.to_csv(out_csv, index=False, encoding="utf-8-sig")

    df_index = df_out[df_out.get("error").isna()].copy() if "error" in df_out.columns else df_out
    index_path = _write_index(out_dir, df_index, title=f"MA Convergence Scan Charts - {base_name}")
    print(f"[OK] saved: {out_csv}")
    print(f"[OK] saved: {index_path}")
    if errors:
        err_csv = out_dir / "errors.csv"
        df_err = df_out[df_out["error"].notna()].copy()
        df_err.to_csv(err_csv, index=False, encoding="utf-8-sig")
        print(f"[WARN] errors={errors}, saved: {err_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
